# Generated by Django 2.0.3 on 2018-03-12 23:15

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('show_id', models.IntegerField()),
                ('url', models.URLField()),
                ('show_type', models.TextField()),
                ('language', models.TextField()),
                ('genres', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('status', models.TextField()),
                ('runtime', models.IntegerField()),
                ('premiered', models.DateField()),
                ('officialSite', models.URLField()),
                ('schedule', django.contrib.postgres.fields.jsonb.JSONField()),
                ('rating', django.contrib.postgres.fields.jsonb.JSONField()),
                ('weight', models.IntegerField()),
                ('network', django.contrib.postgres.fields.jsonb.JSONField()),
                ('webChannel', models.TextField(blank=True, null=True)),
                ('externals', django.contrib.postgres.fields.jsonb.JSONField()),
                ('image', django.contrib.postgres.fields.jsonb.JSONField()),
                ('summary', models.TextField()),
                ('updated', models.TextField()),
                ('links', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
