# Generated by Django 2.0.3 on 2018-03-12 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='officialSite',
            field=models.URLField(blank=True, null=True),
        ),
    ]
