# Generated by Django 2.0.3 on 2018-03-12 23:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_auto_20180312_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='webChannel',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
