# Generated by Django 2.0.3 on 2018-03-13 00:06

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0005_auto_20180312_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='externals',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='genres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='show',
            name='image',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='links',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
