# Generated by Django 2.0.3 on 2018-03-13 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0007_auto_20180312_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='language',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='show_type',
            field=models.TextField(null=True),
        ),
    ]
