# Generated by Django 2.0.3 on 2018-03-15 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shows', '0010_auto_20180312_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowedShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_following', models.BooleanField(default=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.Show')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WatchedEpisode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_seen', models.BooleanField(default=False)),
                ('episode_id', models.IntegerField()),
                ('url', models.URLField(max_length=400)),
                ('name', models.TextField()),
                ('season', models.IntegerField()),
                ('number', models.IntegerField()),
                ('air_time', models.TimeField()),
                ('air_date', models.DateField()),
                ('air_stamp', models.DateTimeField()),
                ('summary', models.TextField()),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_episode', to='shows.FollowedShow')),
            ],
            options={
                'ordering': ['season', 'number'],
            },
        ),
        migrations.AddField(
            model_name='show',
            name='followers',
            field=models.ManyToManyField(through='shows.FollowedShow', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='watchedepisode',
            unique_together={('show', 'season', 'episode_id')},
        ),
    ]
