# Generated by Django 2.0.3 on 2018-03-15 15:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0011_auto_20180315_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='followedshow',
            name='followed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
